[libdefaults]
    default_realm = FIS.EPN.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 10h
    forwardable = true
[realms]
    FIS.EPN.LOCAL = {
        kdc = srv-fis.fis.epn.local
        admin_server = srv-fis.fis.epn.local
    }
